baseURL = "https://frozen-lobster.rohanverma.net"
languageCode = "en-us"
title = "Frozen Lobster"
theme = "bodhi"

[params]
    subtitle = "Preserved goodness"
    avatar = "/images/lobster.jpg"
    author = "Rohan Verma"
    footerMessage = "Daily top stories from lobste.rs"
    featherIconsCDN = true

[[menu.main]]
name = "rohanverma.net"
url = "https://rohanverma.net"
weight = 1

[[menu.main]]
name = "lobste.rs"
url = "https://lobste.rs"
weight = 2

[[menu.nav]]
name = "archives"
url = "/archive"
weight = 2

[[menu.nav]]
name = "posts"
url = "/posts"
weight = 2

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params.fathomAnalytics]
    siteID = "IUAMK"
    serverURL = "fathom.rohanverma.net"
